### ISSUE TITLE
Are you going to release the label files for the clinical notes?

### ISSUE THREAD

**Issue by guanchuwang** [PittNAIL/llms-vote#3]
This is fantastic work for rare disease identification, which takes advantage of the power of LLM in rare disease diagnosis. 

May I ask whether you are going to release the label of the clinical notes? Currently, it still cannot reproduce the results reported in the paper due to a lack of labels (positive or negative).

**Comment by oniani** [comment]
Hi Guanchu -- in the paper, we selected four most frequent rare diseases (Babesiosis, Giant Cell Arteritis, Graft Versus Host Disease, and Cryptogenic Organizing Pneumonia). You could just check if these are present in the context. It is a simple lookup. We have not released MIMIC-IV data or related data due to DUA.
